const products = [
    {
        _id: "1",
        name:"Macbok pro",
        image:"/images/macbook_pro.jpg",
        description:"The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category:"Electronics",
        price: 1299,
        countInStock: 10,
        rating: 0.5,
        numReviews: 12,

    },
    {
        _id: "2",
        name: "Macbok pro",
        image: "/images/macbook_pro.jpg",
        description: "The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category: "Electronics",
        price: 1299,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,

    },
    {
        _id: "3",
        name: "Macbok pro",
        image: "/images/macbook_pro.jpg",
        description: "The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category: "Electronics",
        price: 1299,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,

    },
    {
        _id: "4",
        name: "Macbok pro",
        image: "/images/macbook_pro.jpg",
        description: "The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category: "Electronics",
        price: 1299,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,

    },
    {
        _id: "5",
        name: "Macbok pro",
        image: "/images/macbook_pro.jpg",
        description: "The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category: "Electronics",
        price: 1299,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,

    },
    {
        _id: "6",
        name: "Macbok pro",
        image: "/images/macbook_pro.jpg",
        description: "The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category: "Electronics",
        price: 1299,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,

    },
    {
        _id: "7",
        name: "Macbok pro",
        image: "/images/macbook_pro.jpg",
        description: "The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category: "Electronics",
        price: 1299,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,

    },
    {
        _id: "8",
        name: "Macbok pro",
        image: "/images/macbook_pro.jpg",
        description: "The new MacBook Pro delivers game-changing performance for pros.With the powerful M1 Pro chip to power through your work while enjoying incredible",
        brand: "Apple",
        category: "Electronics",
        price: 1299,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,

    },
];

export default products;